[package]
name = "jaq_py"
version = "0.1.0"
edition = "2021"
description = "Python bindings for jaq, a jq clone written in Rust"
license = "MIT"
repository = "https://github.com/filipsnastins/jaq-py"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
jaq-core = "3.0.0-beta"
jaq-json = "2.0.0-beta"
jaq-std = "3.0.0-beta"
mimalloc = { version = "0.1.48", default-features = false }
num-bigint = "0.4"
pyo3 = { version = "0.28", features = ["extension-module", "num-bigint"] }
