name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        run: |
          rustup update stable && rustup default stable
          rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

      - name: Set up zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.15.1

      - name: Set up uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          python-version: 3.13
          enable-cache: true

      - name: Install dependencies
        run: make install

      - name: Build, lint and test
        run: make ci

      - name: Build distribution wheels
        run: make build-dist

      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: wheels
          path: target/wheels/*.whl
